# Generated by Django 6.1.1 on 2026-09-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_weightrecord_bodymeasurementrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressrecord',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='progressrecord',
            table='progress_progressrecord',
        ),
    ]
