# Generated by Django 6.1.1 on 2026-09-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_new_measurement_tracking'),
        ('progress', '0003_alter_progressrecord_options_and_more'),
    ]

    operations = [
    ]
