# Generated by Django 6.1.1 on 2026-09-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progress_photos_remove_dietitian_update'),
        ('progress', '0004_merge_20260918_1719'),
    ]

    operations = [
    ]
