# Generated by Django 6.1.1 on 2026-09-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_progressphotoset'),
        ('progress', '0005_merge_20260918_1930'),
    ]

    operations = [
    ]
