# Generated by Django 6.1.1 on 2026-09-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='health_goals',
            new_name='health_goal',
        ),
    ]
