# Generated by Django 6.1.1 on 2026-09-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('calories_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MORNING_SNACK', 'Morning Snack'), ('LUNCH', 'Lunch'), ('EVENING_SNACK', 'Evening Snack'), ('DINNER', 'Dinner')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dietplan')),
            ],
        ),
    ]
