# Generated by Django 6.1.1 on 2026-09-17 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Option 1, Choose ONE', max_length=200)),
                ('instruction', models.CharField(blank=True, help_text='Example: Choose ONE', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='diet_plan',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(blank=True, help_text='Example: Fat Loss, Toned Body & Fat Loss', max_length=200),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='plan_code',
            field=models.CharField(blank=True, help_text='Optional short code, e.g. C78', max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, help_text='Preparation notes, e.g. raw weight, air fried'),
        ),
        migrations.AddField(
            model_name='meal',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.CharField(blank=True, help_text='Example: 25, 60-80, 2', max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='unit',
            field=models.CharField(blank=True, help_text='Example: g, ml, tablet, rotis', max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(help_text='Example: Roasted makhana, Chicken breast', max_length=200),
        ),
        migrations.AddField(
            model_name='meal',
            name='option_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.optionsection'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Breakfast, Lunch, Evening Snack', max_length=200)),
                ('timing', models.CharField(blank=True, help_text='Example: 8:00 AM, 15 minutes before breakfast', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='nutrition.dietplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='optionsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_sections', to='nutrition.section'),
        ),
        migrations.AddField(
            model_name='meal',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.section'),
        ),
    ]
