# Generated by Django 6.1.1 on 2026-09-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_optionsection_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('option_section__isnull', True), ('section__isnull', False)), models.Q(('option_section__isnull', False), ('section__isnull', True)), _connector='OR'), name='meal_has_exactly_one_parent'),
        ),
    ]
