# Generated by Django 6.1.1 on 2026-09-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_meal_meal_has_exactly_one_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='plan_code',
        ),
    ]
