# Generated by Django 6.1.1 on 2026-09-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Name shown publicly on the website.', max_length=100)),
                ('title', models.CharField(help_text='Example: 12 kg Weight Loss Journey', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Short description of the client's journey.")),
                ('starting_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.CharField(blank=True, help_text='Example: 4 months', max_length=100)),
                ('review', models.TextField(blank=True, help_text='Client testimonial.')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='success_stories/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='success_stories/after/')),
                ('is_published', models.BooleanField(default=False, help_text='Show this success story on the public website.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='clients.clientprofile')),
            ],
        ),
    ]
